---
- hosts: all
  become: yes
  tasks:
            
    - name: Backup existing config file
      command: cp /etc/mosquitto/mosquitto.conf /etc/mosquitto/mosquitto.conf.original
       
    - name: Edit the mosquitto config file
      become: yes
      become_method: sudo
      blockinfile:
        path: /etc/mosquitto/mosquitto.conf
        block: |
          listener {{port}}
          protocol mqtt
                    
          allow_anonymous false
          password_file /etc/mosquitto/passwd