---
  - hosts: localhost
    vars: 
       ansible_python_interpreter: /usr/bin/python3
    

    tasks:

      - name: Edit Pipeline definition  
        shell: aws datapipeline put-pipeline-definition --pipeline-id {{pipeline_id}} --parameter-values myS3InputBucket=s3://{{source_bucket}}/{{file_path}} myS3OutputBucket=s3://{{destination_bucket}}/{{file_path}} myLogBucket=s3://{{log_bucket}}/{{log_directory}} mySchedule="{{edit_schedule}}" --pipeline-definition file://CopyActivity.json




        

