---
  - hosts: localhost
    vars: 
       ansible_python_interpreter: /usr/bin/python3
    

    tasks:

      - name: Edit Pipeline definition  
        shell: aws datapipeline put-pipeline-definition --pipeline-id {{pipeline_id}} --parameter-values myAWSCLICmd={{aws_cli_command}} myLogBucket={{log_bucket}}/{{log_directory}} mySchedule="{{edit_schedule}}" --pipeline-definition file://ShellCommandActivity.json

        

